apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: ingress-svr
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: myhost.com
      http:
        paths:
          - path: /api/Platforms
            pathType: Prefix
            backend:
              service:
                name: platformservice-ip-srv
                port:
                  number: 80
          - path: /api/c/Platforms
            pathType: Prefix
            backend:
              service:
                name: commandservice-ip-srv
                port:
                  number: 80
									

